### ISSUE TITLE
Operating a printer having action push button

### ISSUE THREAD

**Issue by Tig392** [borisbu/OctoRelay#154]
Hi,

Would it be possible to add this function for the printer control relay? My printer is powered on by a momentary action push button. I've extended the wires from this to a relay to power it on remotely but have to click the relay on then off every time. If the relay could auto off after 1 second this would be great.

**Comment by RobinTail** [comment]
What kind of printer is this, @Tig392 ?

**Comment by RobinTail** [comment]
https://www.creatbot.com/downloads/CreatBot_User_Manual_V7.3_F430_en.pdf

<img width="747" alt="Screenshot 2023-08-07 at 17 11 23" src="https://github.com/borisbu/OctoRelay/assets/13189514/c67bf253-cbf3-4ee4-bd5a-5c6e86d99b18">

**Comment by RobinTail** [comment]
The problem with sending a short ON-OFF signal to such a device is that it's impossible to figure out its state.
The plugin implementation implies a one-to-one relationship between:

- pin state
- relay state
- device state

Thus, toggling the pin toggles the device and reading the pin state tells the device state.

I'd suppose that there should be a way to connect the relay somewhere deeper to the device circuit instead of its button. There should be some electrical component that finally transforms the pushes of that button into a stable HIGH/LOW voltage.

I'm going to ask my electronics engineer friend about that, @Tig392

**Comment by RobinTail** [comment]
Or maybe it would be even easier to make some converter from relay signal to an impulse for that button. I believe I read an article on how to do similar thing to ATX power supply of a PC.

**Comment by RobinTail** [comment]
This topic on StackExchange is about similar problem, there are a lot of circuit schemas in comments for different cases.

https://electronics.stackexchange.com/questions/555261/how-to-toggle-relay-with-single-push-button

**Comment by RobinTail** [comment]
@Tig392 , could you confirm that there are only two wires connected to the power button?

![image](https://github.com/borisbu/OctoRelay/assets/13189514/2fffa3ed-9c82-4a8c-8cb3-1805315a469d)

Does the manufacturer provide an electrical diagram of the machine?

**Comment by RobinTail** [comment]
> > Introducing the new event: After Turned ON.

> Thanks :-)

Does it solve this issue for you, @Tig392
