### ISSUE TITLE
ON before printing is "stuck" activated, despite NOT being activated in settings!

### ISSUE THREAD

**Issue by IAmOrion** [borisbu/OctoRelay#52]
<img width="707" alt="Screenshot 2022-05-26 at 00 44 30" src="https://user-images.githubusercontent.com/3501380/170387285-918149d4-5dd0-4d12-9626-6d1715c62809.png">

As you can see in my screenshot, "ON before printing" is _NOT_ ticked/active.  Yet, every time I start a print, the relay turns on! 
With my relay board, the inverted output is required.  For all intents and purposes it works as expected if I manually toggle the relay control.  It also correctly turns OFF when a print is finished as expected.  I just don't want it turning on when a print starts... but for some reason it does.

**Comment by shooter-z** [comment]
Can confirm. Octorelay 1.2.0 running on raspberry pi.
It is not a display bug, since behaviour is the same whenever "ON before printing" is enabled or disabled.

**Comment by IAmOrion** [comment]
I'm assuming this plugin is dead/no longer supported. :(

**Comment by hcooper** [comment]
I've not tested your exact problem, however I fixed an issue with "on before printing" not working for me.

https://github.com/borisbu/OctoRelay/pull/55

The issue was that the `print_started()` function, was processing all relay configs, not just the "enabled ones". At but chance the default configs were trying to use the same pin as me.

From your screenshot I see you're using pin 23. That's the same pin the default config for Relay 4 uses. Until my PR is committed, try changing Relay 4 config to a different/fake pin and see if that fixes your problem.

**Comment by IAmOrion** [comment]
@hcooper - well done discovering that! That fixed the problem for me, thanks for the info.

**Comment by RobinTail** [comment]
🚀  @IAmOrion , the issue should be fixed in v1.4.1.
Please check it out, and in case it's not, please create another issue.
